version: 2
jobs:
  build:
    working_directory: ~/unit-testing-london
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn setup
          command: |
            sudo npm install -g yarn
            yarn
      - save_cache:
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: Test
          command: |
            yarn test
      